#Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, ‘8.0’

target 'Base' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Base
  
  #网络
  pod 'AFNetworking', '~> 3.0'
  
  #布局
  pod 'Masonry'
  
  #rac
  pod 'ReactiveCocoa', '~> 2.0'
  
  #pop
  pod 'pop', '~> 1.0'
  
  #过渡弹框
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'SVProgressHUD'
  
  
  #加密
  pod 'CocoaSecurity'
  
  #存储在钥匙链
  pod 'SAMKeychain'
  
  #debug工具
  pod 'FLEX', '~> 2.0', :configurations => ['Debug']
  
  #内存泄漏工具
  pod 'MLeaksFinder', :configurations => ['Debug']
  
  
  #圆角
  pod 'ZYCornerRadius', '~> 1.0.2'
  
  
  #block
  pod 'BlocksKit'
  
  #颜色
  pod 'Colours'
  
  
  #刷新
  pod 'MJRefresh'
  
  
  #cell
  pod 'UITableView+FDTemplateLayoutCell'
  
  
  #yykit
  pod 'YYKit'
  
  
  #数据库
  pod'FMDB'
  
  
  #bug管理
  pod 'Bugly'
  
  #键盘
  pod 'IQKeyboardManager'
  
  
  #模型
  pod 'MJExtension'
  
  
  #图片缓存
  pod 'SDWebImage', '~> 4.0.0'
  
  
  #轮播图
  pod 'SDCycleScrollView','~> 1.73'
  
  
  
  
  

  target 'BaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
